[package]
name = "blockz"
version = "0.1.0"
authors = ["cezarmathe <me@cezarmathe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "blockz_derive",
]

[dependencies]
blockz_derive = { path = "./blockz_derive" }

anyhow      = "1.0.38"
async-trait = "0.1.42"
once_cell   = "1.5.2"
serde       = "1.0.121"

[dependencies.tokio]
version = "1.1.0"
default_features = false
features = ["full"]

[features]
default = ["singleton_generics"]

# Pass this feature to blockz_derive.
no_absolute_paths = ["blockz_derive/no_absolute_paths"]

# singleton features
singleton_generics = ["blockz_derive/singleton_generics"]
singleton_boxes    = ["blockz_derive/singleton_boxes"]
