[package]
name = "blockz"
version = "0.1.0"
authors = ["cezarmathe <me@cezarmathe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "blockz_derive",
]

[dependencies]
blockz_derive = { path = "./blockz_derive" }

anyhow      = "^1.0"
async-trait = "^0.1"
once_cell   = "^1.5"
serde       = "^1.0"

[features]
default = []

# Pass this feature to blockz_derive.
no_absolute_paths = ["blockz_derive/no_absolute_paths"]
